### ISSUE TITLE
gsw_t_freezing_poly calculation - gsw_check_functions gives "failed test" message

### ISSUE THREAD

**Issue by TEOS-10** [TEOS-10/GSW-Fortran#1]
The Matlab version of gsw_t_freezing_poly uses an alternative method (via ct_freezing_poly and t_from_ct) to calculate the freezing temp. I've configured the Fortran version to use the more efficient direct from poly method. Consequently gsw_check_functions gives a "failed test" message because the values from the two methods are slightly different. We need to reconfigure gsw_check_functions with a new value for the freezing temp or revert to the alternative method of calculating the freezing temp.

**Comment by hylandg** [comment]
Fixed - reverted to alternative calculation method (same as Matlab).

From Paul:
"t_freezing_poly - Copy the method in matlab that uses t_from_CT  and CT_freezing_poly.
I did make the polynomial that is in respect to t but I am not in favour of its use as we expect people to be using CT not t."
