### ISSUE TITLE
Runtime error with Intel Fortran

### ISSUE THREAD

**Issue by aerorahul** [TEOS-10/GSW-Fortran#13]
The following line at L277 in  ``toolbox/gsw_geo_strf_dyn_height.f90``:

    pseq = (/ (p2-pstep*i, i=n-1,0,-1) /)

causes an error when ``gsw_check`` test is executed.

All tests pass successfully, when L277 is replaced with:

    do i=n-1,0,-1
        pseq(i) = p2-pstep*i
    end do

Here are the compiler and compiler flags being used:

    FC:=ifort
    FFLAGS:=-g -traceback -warn all

**Comment by hylandg** [comment]
Hi Rahul,

The replacement code segment you suggested for line 277 is not equivalent to the original ... 
```fortran
pseq = (/ (p2-pstep*i, i=n-1,0,-1) /)
```
It needs to be ...
```fortran
do i=n-1,0,-1
    pseq(n-i) = p2-pstep*i
end do
```
Can you please send me the error message you get when you run `gsw_check`. This may help me to understand what may be causing the problem. Thanks.

Regards,
Glenn.

**Comment by hylandg** [comment]
Hi Rahul,

I found a machine that had the Intel compiler installed and ran a few tests to see what was causing the problem. If you change line 277 of `toolbox/gsw_geo_strf_dyn_height.f90` to the following it should fix the problem ...
```fortran
pseq(1:n) = (/ (p2-pstep*i, i=n-1,0,-1) /)
```
Cheers,
Glenn.

**Comment by aerorahul** [comment]
Hi Glenn,

Thank you for providing a patch. I tried the fix and it now works for both GNU as well as Intel Fortran compilers.

Thanks,
Rahul
