### ISSUE TITLE
gsw_saar_init - new initialisation routine to load gsw_data_v3_0.dat into memory

### ISSUE THREAD

**Issue by hylandg** [TEOS-10/GSW-Fortran#6]
In order to allow all saar related routines be be elemental, the code that loads data from `gsw_data_v3_0.dat` into memory needs to be in a separate routine (ie. elemental functions cannot do any i/o, or change global data). This routine `gsw_saar_init` needs to be called once by the user prior to any call to a saar related function. This places an additional burden on the user, but there doesn't seem to be any alternative method of getting the data into memory.

**Comment by hylandg** [comment]
Note that the C version of GSW has stored the data from `gsw_data_v3_0.dat` into static arrays. It would be worthwhile looking at whether this was also possible in Fortran - but we might run into continuation line limits (Fortran 95 standard says a maximum of 39 lines are allowed).

**Comment by epitalon** [comment]
I plan to make this change: replace netCDF data with static arrays. I'll make a fork.

**Comment by hylandg** [comment]
All done with commit 6d1d98c475495b0bcb614c60448abad050d43a6f
