### ISSUE TITLE
check_functions fails for "ice/sea-ice thermodynamic interaction" functions

### ISSUE THREAD

**Issue by hylandg** [TEOS-10/GSW-Fortran#9]
Check values have been derived from the Matlab functions which use _CT_exact versions of the enthalpy/freezing functions rather than the _poly versions. Need new check values or a reduced "computation accuracy" value.

**Comment by PaulMBarker** [comment]
Need new check values and new computational accuracy.

**Comment by hylandg** [comment]
Fixed in v3.05
